### PR TITLE
Some Repair, Some aesthetic changes, safety adjustments

### PR DESCRIPTION
**Pull request by awunes**
Fixed incorrect character replacement.

Added nitrotype's icon to AHK's exe
Changed to a new color of the AHK's exe icon (nitrotype's icon but color modified slightly)

Changed the typing speed from 10ms ~ 450wpm to 100ms ~ 100wpm. Reduces risk of banning

### CODE REVIEW

**Comment by itzTheMeow** [comment]
this repo is dead

i actually made a better version of this that uses puppeteer, but havent released it to the public

**Comment by awunes** [comment]
well okay then :) ... Might merge it in the mean time, no? I mean until the new one, "that uses puppeteer," is available. Never heard of puppeteer ... Thanks for that :) Love to learn of new languages and things :)

**Comment by itzTheMeow** [comment]
https://github.com/puppeteer/puppeteer

**Comment by awunes** [comment]
Sorry I meant that I'd already found it from the name :) thanks for providing the link anyway :). Also, I'm loving your Mineception. Haven't registered with top.gg yet so can't rate/vote/whatever there but will :)

That all said, I'm not familiar with what it means for a repo to be dead ... Can they not be merged any longer? Are they no longer available to be found by searching? Thanks for helping an old man like me understand more :)

**Pull request closed without merging**
